# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1929, 994)
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-350, -50, 2920, 1642))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/B.G/back-ground.webp"))
        self.bg_1.setObjectName("bg_1")


        self.gif3 = QtWidgets.QLabel(self.centralwidget)
        self.gif3.setGeometry(QtCore.QRect(-40, 40, 421, 251))
        self.gif3.setText("")
        self.gif3.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/VoiceReg/jarvis_jj.gif"))
        self.gif3.setObjectName("gif3")


        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, 410, 371, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/ExtraGui/Earth.gif"))
        self.label_2.setObjectName("label_2")


        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 780, 391, 191))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/ExtraGui/initial.gif"))
        self.label_4.setObjectName("label_4")


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, -10, 1261, 811))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/B.G/Iron_Template_1.gif"))
        self.label.setObjectName("label")


        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1220, 30, 691, 391))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/ExtraGui/Hero_Template.gif"))
        self.label_6.setObjectName("label_6")


        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1320, 670, 631, 331))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/B.G/gyhf.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")


        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(730, 790, 391, 81))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")


        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(740, 800, 371, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Downloads/G.U.I Material-20221126T185922Z-001/G.U.I Material/Buttons/Start.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")


        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1420, 720, 431, 71))
        self.label_7.setObjectName("label_7")


        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1430, 890, 391, 61))
        self.label_8.setObjectName("label_8")

        
        self.bg_1.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.gif3.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        JarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        self.label_7.setText(_translate("JarvisUI", "TextLabel"))
        self.label_8.setText(_translate("JarvisUI", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
